name: Blog Posts workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 * * * *' # Runs every hour, on the hour
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Pull in medium posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: MEDIUM
          feed_list: "https://neobeppe.medium.com/feed"
      
      - name: Pull in dev.to posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: DEVTO
          feed_list: "https://dev.to/feed/neobeppe"
